 image: ubantu: 22.04

 stages:
  - prepare
  - build

 variables:
       JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-amd64"
       ANDROID_HOME: "/sdk"
       ANDROID_SDK_ROOT: "/sdk"
       GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
       PATH: "$JAVA_HOME/bin:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"

 before_script:
      - apt-get update -qq
      - apt-get install -y openjdk-17-jdk wget unzip git curl
      - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs
      - node -v
      - npm -v
      - npm install
      - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      - export PATH=$JAVA_HOME/bin:$PATH
      - mkdir -p /sdk/cmdline-tools
      - cd /sdk/cmdline-tools
      - wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O commandlinetools.zip
      - unzip -o commandlinetools.zip 
      - mkdir -p /sdk/cmdline-tools/latest
      - mv cmdline-tools/* /sdk/cmdline-tools/latest/ || true
      - yes | /sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/sdk --licenses
      - yes | /sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/sdk "platform-tools" "build-tools;34.0.0" "platforms;android-34"
      - cd $CI_PROJECT_DIR

 prepare:
  stage: prepare
  script:
        - echo "Environment prepared successfully"
        - echo "Decoding google-services.json..."
        - echo "GOOGLE_SERVICES_JSON_BASE64" | base64 -d > android/app/google-services.json
        - echo "Decoding release.keystore..."
        - mkdir -p android/app
        - echo "$RELEASE_KEYSTORE_BASE64" | base64 -d > android/app/release.keystore
        - echo "storeFile=android/app/release.keystore" > keystore.properties
        - echo "storePassword=$RELEASE_KEYSTORE_PASSWORD" >> keystore.properties
        - echo "keyAlias=$RELEASE_KEY_ALIAS" >> keystore.properties
        - echo "keyPassword=$RELEASE_KEY_PASSWORD" >> keystore.properties
        - keytool -list -v -keystore android/app/release.keystore -storepass "$RELEASE_KEYSTORE_PASSWORD"

  build_apk:
  stage: build
  script:
         - echo "Starting build..."
         - node generateBundle.js
         - chmod +x gradlew
         - ./gradlew clean
         - ./gradlew assembleRelease

  artifacts:
  paths: 
         - android/app/build/outputs/apk/release/app-release.apk
  expire_in: 1 week
  only:
        - main