image: node:20

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  ANDROID_COMPILE_SDK: "34"
  ANDROID_BUILD_TOOLS: "34.0.0"
  ANDROID_SDK_TOOLS: "9477386"
  ANDROID_NDK_VERSION: "26.1.10909125"

before_script:
  - apt-get update -qq
  - apt-get install -y openjdk-17-jdk wget unzip
  - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
  - export PATH=$JAVA_HOME/bin:$PATH
  - java -version
  - node -v
  - chmod +x ./gradlew

stages:
  - dependencies
  - setup_files
  - build_bundle
  - build_apk

install_dependencies:
  stage: dependencies
  script:
   - yarn install --frozen-lockfile
   - npx react-native config
  cache:
    paths:
     - node_modules/
    key: ${CI_COMMIT_REF_SLUG}
  artifacts:
    paths:
     - node_modules/

  setup_android:
     stage: dependencies
     script:
       - wget -q https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip -0 android-sdk.zip
       - unzip -q android-sdk.zip -d /usr/local/android-sdk
       - export ANDROID_SDK_ROOT=/usr/local/android-sdk
       - export PATH=$ANDROID_SDK_ROOT/cmdline-tools/bin:$PATH
       - yes | sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platforms;android-${ANDROID_COMPILE_SDK}" "build-tools;${ANDROID_BUILD_TOOLS}" "ndk;${ANDROID_NDK_VERSION}"
       - export PATH=$ANDROID_SDK_ROOT/platform-tools:$PATH
     artifacts:
        paths:
        - /user/local/android-sdk/

  setup_config_files:
    stage: setup_files
    script:
        - echo "$RELEASE_KEYSTORE_BASE64" | -d > android/app/release.keystore
        - echo "storeFile=release.keystore" > keystore.properties
        - echo "storePassword=$RELEASE_KEYSTORE_PASSWORD" >> keystore.properties
        - echo "keyAlias=$RELEASE_KEY_ALIAS" >> keystore.properties
        - echo "keyPassword=$RELEASE_KEY_PASSWORD" >> keystore.properties
        - echo "keystore created"

        - echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 -d > android/app/google-services.json
        - echo "google-services.json created"

        - ls -la android/app/release.keystore
        - ls -la android/app/google-services.json
        - file android/app/google-services.json
    dependencies:
        - install_dependencies
    artifacts:
       paths:
        - android/app/release.keystore
        - android/app/google-services.json
       expire_in: 1 hour

  generate_bundle:
      stage: build_bundle
      script:
         - node generateBundle.js
         - ls -la android/app/build/generated/assets/
      dependencies:
         - install_dependencies
         - setup_config_files
      artifacts:
         paths:
          - android/app/build/generated/
         expire_in: 1 hour

      build_apk:
        stage: build_apk
        script:
           - export ANDROID_SDK_ROOT=/usr/local/android-sdk
           - export PATH=$ANDROID_SDK_ROOT/cmdline-tools/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH

           - ls -la android/app/release.keystore
           - ls -la android/app/google-services.jsom
           - ls -la android/app/build/generated/assets/

           - ./gradlew clean
           - ./gradlew :app:assembleRelease --no-daemon --max-workers=2

           - ls -la android/app/build/outputs/apk/release/
           - file android/app/build/outputs/apk/release/app-release.apk

        dependencies:
           - setup_android
           - generate_bundle
           - setup_config_files
        artifacts:
           paths:
             - android/app/build/outputs/apk/release/app-release.apk
           expire_in: 1 week
           only:
             - main

