# Enable caching and build optimizations
org.gradle.caching=true
org.gradle.parallel=false
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx2024m -Dfile.encoding=UTF-8  
# Enable AndroidX support
android.useAndroidX=true
android.enableJetifier=true
android.ndkVersion=26.1.10909125
# Hermes Engine Support for React Native
hermesEnabled=true
newArchEnabled=true
# Debugging settings
org.gradle.debug=false
REACT_NATIVE_BUILD_FROM_SOURCE=true
kotlin.version=1.9.24
androidGradlePluginVersion=8.4.0
# Keystore
RELEASE_KEY_ALIAS=release







