name: Build Android APK
  
on:
 push:
  branches: 
    - main
 workflow_dispatch:

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout repository
     uses: actions/checkout@v4
   
   - name: Setup Node.js
     uses: actions/setup-node@v4
     with:
      node-version: 20
   
   - name: Setup Java 
     uses: actions/setup-java@v4
     with: 
       distribution: 'temurin'
       java-version: 17
   
   - name: Setup Android SDK
     uses: android-actions/setup-android@v3

   - name: Install dependencies
     run: npm install
  
   - name: Generate Hermes + newArch bundle
     run: node generateBundle.js

   - name: Make gradlew executable
     run: chmod +x ./gradlew

   - name: Create keystore.properties
     run: |
         echo "storeFile=android/app/release.keystore"
         > $GITHUB_WORKSPACE/keystore.properties
         echo "storePassword=${{secrets.KEYSTORE_PASSWORD}}" >> $GITHUB_WORKSPACE/keystore.properties
         echo "keyAlias=${{secrets.KEY_ALIAS}}" >> $GITHUB_WORKSPACE/keystore.properties
         echo "keyPassword=${{secrets.KEY_PASSWORD}}" >> $GITHUB_WORKSPACE/keystore.properties

   - name: Decode and setup keystore
     run: |
      echo "${{secrets.KEYSTORE_BASE64}}" | base64 --decode > android/app/release.keystore

   - name: Verify keystore setup (short)
     run: |
       echo "----storeFile line----"
        grep storeFile keystore.properties || echo "storeFile missing"
       echo "----keystore file----"
       if [ -f android/app/release.keystore ]; then
       echo "release.keystore exists" 
       else
       echo "release.keystore missing"
         fi
       
   - name: Build Release APK 
     run: ./gradlew assembleRelease 

   - name: Upload APK artifact
     uses: actions/upload-artifact@v4
     with:
       name: app-release
       path: android/app/build/outputs/apk/release/app-release.apk

